spring:
  datasource:
#    url: ${SPRING_DATASOURCE_URL}
#    username: ${SPRING_DATASOURCE_USERNAME}
#    password: ${SPRING_DATASOURCE_PASSWORD}
     url: jdbc:mysql://localhost:3306/self
     username: root
     password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
